apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-chunks-downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-chunks-downloader
  template:
    metadata:
      labels:
        app: mag20-chunks-downloader
    spec:
      containers:
        - image: mag20/go-chunks-downloader
          name: mag20-chunks-downloader
          env:
            - name: AWS_STORAGE_URL
              value: http://mag20-aws-storage:8002/
            - name: TRACING_CONNECTION
              value: "jaeger-agent.istio-system:5775"
          ports:
            - containerPort: 8005
              name: downloader-http
              protocol: TCP
            - containerPort: 8888
              name: download-health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: download-health
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: download-health
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-chunks-downloader
spec:
  type: NodePort
  ports:
    - port: 8005
      name: "downloader-http"
      protocol: TCP
      targetPort: downloader-http
    - port: 8888
      name: "downloader-health"
      protocol: TCP
      targetPort: download-health
  selector:
    app: mag20-chunks-downloader