apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-hls-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-hls-stream
  template:
    metadata:
      labels:
        app: mag20-hls-stream
    spec:
      containers:
        - image: mag20/go-hls-stream-player
          name: mag20-hls-stream
          env:
            - name: PORT
              value: "8006"
            - name: URL
              value: https://51.116.109.32/hls-stream/
            - name: TIMESHIFT_GRPC_SERVER
              value: mag20-timeshift
            - name: TIMESHIFT_GRPC_PORT
              value: "9004"
            - name: TRACING_CONNECTION
              value: "jaeger-agent.istio-system:5775"
          ports:
            - containerPort: 8006
              name: hls-http
              protocol: TCP
            - containerPort: 8888
              name: hls-http-health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: hls-http-health
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: hls-http-health
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-hls-stream
spec:
  type: NodePort
  ports:
    - port: 8006
      name: "hls-http"
      protocol: TCP
      targetPort: hls-http
    - port: 8888
      name: "hls-http-health"
      protocol: TCP
      targetPort: hls-http-health
  selector:
    app: mag20-hls-stream