apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-media-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-media-metadata
  template:
    metadata:
      labels:
        app: mag20-media-metadata
    spec:
      containers:
        - image: mag20/media-metadata
          name: mag20-media-metadata
          env:
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_OPENTRACING_JAEGER_AGENTHOST
              value: "jaeger-agent.istio-system"
            - name: KUMULUZEE_OPENTRACING_JAEGER_SAMPLER_HTTPHOSTPORT
              value: http://jaeger-collector.istio-system:14268/api/traces
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:mysql://mag-uros20.cd0nfxw2grsa.eu-central-1.rds.amazonaws.com:3306/Media
          ports:
            - containerPort: 8001
              name: media-meta-http
              protocol: TCP
            - containerPort: 9002
              name: media-meta-grpc
          livenessProbe:
            httpGet:
              path: /health/live
              port: media-meta-http
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: media-meta-http
            initialDelaySeconds: 60
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-media-metadata
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      name: "media-meta-http"
      protocol: TCP
      targetPort: media-meta-http
    - port: 9002
      name: "media-meta-grpc"
      protocol: TCP
      targetPort: media-meta-grpc
  selector:
    app: mag20-media-metadata