apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-media-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-media-manager
  template:
    metadata:
      labels:
        app: mag20-media-manager
    spec:
      containers:
        - image: mag20/media-manager
          name: mag20-media-manager
          env:
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: APPPROPERTIES_RABBITMQ_HOST
              value: mag20-rmq
            - name: APPPROPERTIES_SERVICES_AWSSTORAGE_URL
              value: http://mag20-aws-storage:8002/
            - name: APPPROPERTIES_SERVICES_MEDIAMETADATA_URL
              value: http://mag20-media-metadata:8001/
            - name: APPPROPERTIES_SERVICES_MEDIACHUNKS_URL
              value: http://mag20-media-chunks:8004/
            - name: KUMULUZEE_GRPC_CLIENTS0_ADDRESS
              value: mag20-aws-storage
            - name: KUMULUZEE_GRPC_CLIENTS0_PORT
              value: "9001"
            - name: KUMULUZEE_GRPC_CLIENTS1_ADDRESS
              value: mag20-media-metadata
            - name: KUMULUZEE_GRPC_CLIENTS1_PORT
              value: "9002"
            - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
              value: http://etcd:2379/health
            - name: KUMULUZEE_HEALTH_CHECKS_RABBITHEALTHCHECK_CONNECTIONURL
              value: amqp://uros:uros123@mag20-rmq:5672
            - name: KUMULUZEE_OPENTRACING_JAEGER_AGENTHOST
              value: jaeger-agent.istio-system
            - name: KUMULUZEE_OPENTRACING_JAEGER_SAMPLER_HTTPHOSTPORT
              value: http://jaeger-agent.istio-system:5775
          ports:
            - containerPort: 8003
              name: manager-http
          livenessProbe:
            httpGet:
              path: /health/live
              port: manager-http
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: manager-http
            initialDelaySeconds: 60
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-media-manager
spec:
  type: NodePort
  ports:
    - port: 8003
      name: "manager-http"
      protocol: TCP
      targetPort: manager-http
  selector:
    app: mag20-media-manager