apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-media-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-media-metadata
  template:
    metadata:
      labels:
        app: mag20-media-metadata
    spec:
      containers:
        - image: mag20/media-metadata
          name: mag20-media-metadata
          env:
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
          ports:
            - containerPort: 8001
              name: media-meta-http
              protocol: TCP
            - containerPort: 9002
              name: media-meta-grpc
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-media-metadata
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      name: "media-meta-http"
      protocol: TCP
      targetPort: media-meta-http
    - port: 9002
      name: "media-meta-grpc"
      protocol: TCP
      targetPort: media-meta-grpc
  selector:
    app: mag20-media-metadata