apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-worker-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-worker-publisher
  template:
    metadata:
      labels:
        app: mag20-worker-publisher
    spec:
      containers:
        - image: mag20/go-publisher-worker
          name: mag20-worker-publisher
          env:
            - name: RABBIT_HOST
              value: "40.114.171.212"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_QUEUE_WORKER
              value: "MEDIA_PUBLISHER"
            - name: RABBIT_QUEUE_VIDEO_ANALYSIS
              value: "VIDEO_ANALYSIS_QUEUE"
            - name: MEDIA_METADATA_GRPC_SERVER
              value: "20.50.33.248"
            - name: MEDIA_METADATA_GRPC_PORT
              value: "9002"
            - name: CHUNK_METADATA_GRPC_SERVER
              value: "20.50.34.65"
            - name: CHUNK_METADATA_GRPC_PORT
              value: "9003"
            - name: TIMESHIFT_GRPC_SERVER
              value: "52.143.10.61"
            - name: TIMESHIFT_GRPC_PORT
              value: "9004"
            - name: SEQUENCE_SERVICE_GRPC_SERVER
              value: "52.143.8.185"
            - name: SEQUENCE_SERVICE_GRPC_PORT
              value: "9006"
            - name: AWS_STORAGE_GRPC_SERVER
              value: "20.50.233.218"
            - name: AWS_STORAGE_GRPC_PORT
              value: "9001"
          livenessProbe:
            httpGet:
              path: /live
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-worker-publisher
spec:
  type: ClusterIP
  ports:
    - port: 4000
      name: "worker-publisher"
      protocol: TCP
  selector:
    app: mag20-worker-publisher