apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-worker-segmenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-worker-segmenter
  template:
    metadata:
      labels:
        app: mag20-worker-segmenter
    spec:
      containers:
        - image: mag20/go-media-segmenter-worker
          name: mag20-worker-segmenter
          env:
            - name: RABBIT_HOST
              value: "40.114.171.212"
            - name: RABBIT_PORT
              value: "5672"
            - name: AWS_STORAGE_URL
              value: https://20.50.41.82/aws/
            - name: MEDIA_METADATA_GRPC_SERVER
              value: "20.50.33.248"
            - name: MEDIA_METADATA_GRPC_PORT
              value: "9002"
            - name: CHUNK_METADATA_GRPC_SERVER
              value: "20.50.34.65"
            - name: CHUNK_METADATA_GRPC_PORT
              value: "9003"
            - name: AWS_STORAGE_GRPC_SERVER
              value: "20.50.233.218"
            - name: AWS_STORAGE_GRPC_PORT
              value: "9001"
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-worker-segmenter
spec:
  type: ClusterIP
  ports:
    - port: 4002
      name: "worker-segmenter"
      protocol: TCP
  selector:
    app: mag20-worker-segmenter