apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-worker-cutter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-worker-cutter
  template:
    metadata:
      labels:
        app: mag20-worker-cutter
    spec:
      containers:
        - image: mag20/go-media-cutter-worker
          name: mag20-worker-cutter
          env:
            - name: RABBIT_HOST
              value: "40.114.171.212"
            - name: RABBIT_PORT
              value: "5672"
            - name: AWS_STORAGE_URL
              value: https://20.50.41.82/aws/
            - name: MEDIA_METADATA_GRPC_SERVER
              value: "20.50.33.248"
            - name: MEDIA_METADATA_GRPC_PORT
              value: "9002"
            - name: CHUNK_METADATA_GRPC_SERVER
              value: "20.50.34.65"
            - name: CHUNK_METADATA_GRPC_PORT
              value: "9003"
            - name: AWS_STORAGE_GRPC_SERVER
              value: "20.50.233.218"
            - name: AWS_STORAGE_GRPC_PORT
              value: "9001"
          livenessProbe:
            httpGet:
              path: /live
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-worker-cutter
spec:
  type: ClusterIP
  ports:
    - port: 4003
      name: "worker-cutter"
      protocol: TCP
  selector:
    app: mag20-worker-cutter