apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag20-worker-segmenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mag20-worker-segmenter
  template:
    metadata:
      labels:
        app: mag20-worker-segmenter
    spec:
      containers:
        - image: mag20/go-media-segmenter-worker
          name: mag20-worker-segmenter
          env:
            - name: RABBIT_HOST
              value: "51.116.109.40"
            - name: RABBIT_PORT
              value: "5672"
            - name: AWS_STORAGE_URL
              value: https://51.116.109.32/aws/
            - name: MEDIA_METADATA_GRPC_SERVER
              value: "51.116.109.53"
            - name: MEDIA_METADATA_GRPC_PORT
              value: "9002"
            - name: CHUNK_METADATA_GRPC_SERVER
              value: "51.116.97.118"
            - name: CHUNK_METADATA_GRPC_PORT
              value: "9003"
            - name: AWS_STORAGE_GRPC_SERVER
              value: "51.116.109.69"
            - name: AWS_STORAGE_GRPC_PORT
              value: "9001"
          livenessProbe:
            httpGet:
              path: /live
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mag20-worker-segmenter
spec:
  type: ClusterIP
  ports:
    - port: 4002
      name: "worker-segmenter"
      protocol: TCP
  selector:
    app: mag20-worker-segmenter